services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/CSDegreeNavigator
      - NODE_ENV=development
      - TAILWINDCSS_OXIDE=wasm

    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./seed:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mongo_data:
